"""MLX WKV with custom Metal kernels (task 25 option 2).

Uses `mx.fast.metal_kernel` to run the RWKV-v4 WKV recurrence as two
fused Metal compute kernels — one for forward, one for backward. Each
kernel runs one thread per (batch, channel) pair, with the full T-loop
living inside the thread. This avoids the per-timestep Metal-dispatch
overhead that killed the pure-MLX path (3.3% of g5) and the auto-diff
path (1.1% of g5).

Math: ported 1:1 from `vendor/L3TC/models/RWKV_V4/cuda/wkv_cuda.cu`
(MIT, BlinkDL). Also mirrored in `scripts/metal_wkv/wkv.metal` from an
earlier torch-MPS attempt.

Wrapped in `@mx.custom_function` + `.vjp` so the rest of the training
code (`scripts/mlx_rwkv.py`, `scripts/mlx_train_specialist.py`) is
unchanged — it sees a normal MLX op with a hand-written backward.

Pre-exponentiation contract from rwkv_v4_train.py:60-69: raw trainable
`time_decay` comes in, we exponentiate to `w_exp = -exp(time_decay)`
inside the custom_function, and both kernels receive this post-exp
value. gw from the backward kernel is then multiplied by `w_exp` in
the VJP to get d_time_decay (chain rule).
"""
from __future__ import annotations

import mlx.core as mx


# Must underflow in Metal's fp32 exp without producing NaN/Inf.
MIN_VALUE = -1e30


# ---------------------------------------------------------------- Kernels
# One MSL source string for forward, one for backward. The kernel
# signature is generated by mx.fast.metal_kernel from the
# input_names/output_names we declare at kernel construction.
#
# MLX exposes: `{name}` (pointer), `{name}_shape[i]` (int32 dim sizes).

_FWD_SOURCE = """
    uint tid = thread_position_in_grid.x;
    int B = k_shape[0];
    int T = k_shape[1];
    int C = k_shape[2];
    if (tid >= (uint)(B * C)) return;

    int b = int(tid) / C;
    int c = int(tid) - b * C;
    int stride_bc = b * T * C + c;

    float uu = u[c];
    float ww = w[c];

    float p = 0.0f, q = 0.0f, o = MIN_VALUE;

    for (int i = 0; i < T; ++i) {
        int ii = i * C;
        float ki = k[stride_bc + ii];
        float vi = v[stride_bc + ii];

        float no = metal::max(o, uu + ki);
        float A = metal::exp(o - no);
        float Bv = metal::exp(uu + ki - no);
        y[stride_bc + ii] = (A * p + Bv * vi) / (A * q + Bv);

        no = metal::max(ww + o, ki);
        A = metal::exp(ww + o - no);
        Bv = metal::exp(ki - no);
        p = A * p + Bv * vi;
        q = A * q + Bv;
        o = no;
    }
"""

# Backward: two sweeps in one kernel, using per-thread scratch arrays.
# T_MAX must be a compile-time constant in MSL. We use 2048 to match
# the CUDA kernel's Tmax. This caps each thread's stack at ~24 KB which
# Apple7+ GPUs accommodate.
_BWD_SOURCE = """
    constexpr int T_MAX = 2048;
    uint tid = thread_position_in_grid.x;
    int B = k_shape[0];
    int T = k_shape[1];
    int C = k_shape[2];
    if (tid >= (uint)(B * C)) return;
    if (T > T_MAX) return;  // host must validate

    int b = int(tid) / C;
    int c = int(tid) - b * C;
    int stride_bc = b * T * C + c;

    float y_s[T_MAX];
    float z_s[T_MAX];
    float zexp_s[T_MAX];

    float uu = u[c];
    float ww = w[c];
    float gw_acc = 0.0f, gu_acc = 0.0f;
    float p = 0.0f, q = 0.0f;
    float dpdw = 0.0f, dqdw = 0.0f;
    float o = MIN_VALUE;

    for (int i = 0; i < T; ++i) {
        int ii = i * C;
        float ki = k[stride_bc + ii];
        float vi = v[stride_bc + ii];
        float gyi = gy[stride_bc + ii];

        float no = metal::max(o, ki + uu);
        float A = metal::exp(o - no);
        float Bv = metal::exp(ki + uu - no);

        float num = A * p + Bv * vi;
        float iden = 1.0f / (A * q + Bv);

        y_s[i] = num * iden;
        z_s[i] = iden;
        zexp_s[i] = ki + uu - no;

        gw_acc += gyi * (dpdw - dqdw * y_s[i]) * iden * A;
        gu_acc += gyi * (vi - y_s[i]) * Bv * iden;

        no = metal::max(ww + o, ki);
        A = metal::exp(ww + o - no);
        Bv = metal::exp(ki - no);
        dpdw = A * (p + dpdw);
        dqdw = A * (q + dqdw);
        p = A * p + Bv * vi;
        q = A * q + Bv;
        o = no;
    }

    float gp = 0.0f, gq = 0.0f;
    o = MIN_VALUE;
    for (int i = T - 1; i >= 0; --i) {
        int ii = i * C;
        float ki = k[stride_bc + ii];
        float vi = v[stride_bc + ii];
        float gyi = gy[stride_bc + ii];

        float A = gyi * z_s[i] * metal::exp(zexp_s[i]);
        float Bv = metal::exp(ki + o);
        gk[stride_bc + ii] = A * (vi - y_s[i]) + Bv * (gp * vi + gq);
        gv[stride_bc + ii] = A + Bv * gp;

        float no = metal::max(ww + o, zexp_s[i] - ki - uu);
        A = metal::exp(ww + o - no);
        Bv = gyi * z_s[i] * metal::exp(zexp_s[i] - ki - uu - no);
        gp = A * gp + Bv;
        gq = A * gq - Bv * y_s[i];
        o = no;
    }

    // Store per-(b, c) accumulators. Host-side sum_across_batch gives
    // the actual gw, gu grads over all batch lanes.
    int bc = b * C + c;
    gw[bc] = gw_acc;
    gu[bc] = gu_acc;
"""

_HEADER = f"""
#define MIN_VALUE ({MIN_VALUE}f)
"""

_fwd_kernel = mx.fast.metal_kernel(
    name="wkv_forward",
    input_names=["w", "u", "k", "v"],
    output_names=["y"],
    source=_FWD_SOURCE,
    header=_HEADER,
)

_bwd_kernel = mx.fast.metal_kernel(
    name="wkv_backward",
    input_names=["w", "u", "k", "v", "gy"],
    output_names=["gw", "gu", "gk", "gv"],
    source=_BWD_SOURCE,
    header=_HEADER,
)


def _launch_forward(w_exp, u, k, v):
    B, T, C = k.shape
    total = B * C
    # Threadgroup size: use 32 to match the reference CUDA kernel
    # (`threadsPerBlock = min(C, 32)`). MLX requires grid to be a
    # multiple of threadgroup size per-dim, so we round up.
    tpg = min(total, 32)
    grid_x = ((total + tpg - 1) // tpg) * tpg
    (y,) = _fwd_kernel(
        inputs=[w_exp, u, k, v],
        grid=(grid_x, 1, 1),
        threadgroup=(tpg, 1, 1),
        output_shapes=[k.shape],
        output_dtypes=[k.dtype],
    )
    return y


def _launch_backward(w_exp, u, k, v, gy):
    B, T, C = k.shape
    assert T <= 2048, f"T_MAX=2048 in kernel; got T={T}"
    total = B * C
    tpg = min(total, 32)
    grid_x = ((total + tpg - 1) // tpg) * tpg
    gw, gu, gk, gv = _bwd_kernel(
        inputs=[w_exp, u, k, v, gy],
        grid=(grid_x, 1, 1),
        threadgroup=(tpg, 1, 1),
        output_shapes=[(B, C), (B, C), k.shape, k.shape],
        output_dtypes=[k.dtype, k.dtype, k.dtype, k.dtype],
    )
    return gw, gu, gk, gv


# ---------------------------------------------------------------- Custom op
@mx.custom_function
def wkv(time_decay: mx.array, time_first: mx.array,
        k: mx.array, v: mx.array) -> mx.array:
    """WKV recurrence, Metal-kernel-backed.

    time_decay: (C,) trainable. Pre-exp'd to w_exp = -exp(time_decay).
    time_first: (C,) trainable.
    k, v:       (B, T, C).
    returns:    (B, T, C).

    Kernels run in fp32 for numerical stability (the WKV recurrence's
    log-sum-exp needs it). Inputs are cast up and outputs cast back to
    the caller's dtype.
    """
    # Metal kernel runs in fp32 for stability; cast up if needed.
    want_dtype = k.dtype
    if want_dtype != mx.float32:
        time_decay_f = time_decay.astype(mx.float32)
        time_first_f = time_first.astype(mx.float32)
        k_f = k.astype(mx.float32)
        v_f = v.astype(mx.float32)
    else:
        time_decay_f, time_first_f, k_f, v_f = time_decay, time_first, k, v

    w_exp = -mx.exp(time_decay_f)
    y = _launch_forward(w_exp, time_first_f, k_f, v_f)
    if want_dtype != mx.float32:
        y = y.astype(want_dtype)
    return y


@wkv.vjp
def wkv_vjp(primals, cotangent, output):
    time_decay, time_first, k, v = primals
    want_dtype = k.dtype

    if want_dtype != mx.float32:
        time_decay_f = time_decay.astype(mx.float32)
        time_first_f = time_first.astype(mx.float32)
        k_f = k.astype(mx.float32)
        v_f = v.astype(mx.float32)
        gy_f = cotangent.astype(mx.float32)
    else:
        time_decay_f, time_first_f = time_decay, time_first
        k_f, v_f = k, v
        gy_f = cotangent

    w_exp = -mx.exp(time_decay_f)
    gw_per_bc, gu_per_bc, gk, gv = _launch_backward(w_exp, time_first_f, k_f, v_f, gy_f)

    # Reduce across batch and apply the w_exp chain-rule factor for
    # d/d(time_decay) (since w_exp = -exp(time_decay); see module
    # docstring and wkv_cuda.cu:107-110).
    d_time_decay = (gw_per_bc * w_exp).sum(axis=0)
    d_time_first = gu_per_bc.sum(axis=0)

    if want_dtype != mx.float32:
        d_time_decay = d_time_decay.astype(time_decay.dtype)
        d_time_first = d_time_first.astype(time_first.dtype)
        gk = gk.astype(want_dtype)
        gv = gv.astype(want_dtype)

    return d_time_decay, d_time_first, gk, gv
